#!/bin/bash


git submodule update --init --recursive
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Lets get the config...."
echo ""
#pacman -S zsh

if [ -z "$HOME" ]; then
	echo "Critical failure, \$HOME not set."
	echo "Type your full home path (no ~) and hit [ENTER] ex. /home/username"
	read -e HOME 
	echo $HOME
else
	echo "Current home dir: $HOME"
fi

read -p "Please confirm you're using zsh [y] " -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
	#if [ $(chsh -l | grep -c "zsh") == "0" ]; then
	if [ -d "$HOME/.oh-my-zsh/" ]; then
		echo "Installing oh-my-zsh"
		sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
	fi
	if [ -f $DIR/.zshrc ]; then
		ln -fs $DIR/.zshrc $HOME/.zshrc
	else
		echo ".zshrc missing from git folder, skipping..."
	fi
fi

if [ -f /etc/redhat-release ]; then
	echo "Redhat detected"
elif [ -f /etc/debian_version ]; then
	echo "Debian detected"
fi

#Lets move some files
if [ -f $DIR/.vimrc ]; then
	ln -fs $DIR/.vimrc $HOME/.vimrc
else
	echo ".vimrc missing from git folder, skipping..."
fi
if [ -d "$DIR/.vim" ]; then
	ln -fs $DIR/.vim $HOME/.vim
else
	echo ".vim missing from git folder, skipping..."
fi
#
#result=${PWD##*/}
#eval "cd .."
#echo "Deleting"
#eval "rm -rf $result"
